### ISSUE TITLE
Documentation: Unity Installation

### ISSUE THREAD

**Issue by orrblue** [kpwelsh/RobotArmTeleoperation#1]
It would be helpful if the installation instructions included the following unity-specific instructions:
1. To first clone the repo
2. Use Unity Hub and click "Add". Then navigate to the cloned repo
3. Specify which version of Unity the project relies on
4. Whether the project should be opened before or after adding RobotIKNative library and other libraries. As in, please specify at what point in the installation instructions should unity be 1) cloned, 2) added and opened  using unity hub
    -- Right now I haven't found the right to place RobotIKWASM into (see  #4) , and tried opening Unity but it says it has compilation errors. I assume I need RobotIKWASM for it to compile.

**Comment by kpwelsh** [comment]
Added some unity instructions. Point 4 should no longer be an issue when the other issues are addressed.
