### ISSUE TITLE
Documentation: File extension details  

### ISSUE THREAD

**Issue by orrblue** [kpwelsh/RobotArmTeleoperation#3]
In the installation instructions for robot_ik_native, please specify which file specifically needs to be put in Assets/Plugins. Is it the .dll file or a different file? I know it says "dynamic library" but I can only guess that means .dll, and I don't even know what dll or dynamic library is exactly. So please make sure to specify the exact file name and extension for all files in the installation instructions.

**Comment by kpwelsh** [comment]
resolved by commit 316cf3c59a98f1bbe2d5a88b527ecb719b24c7cc
