### ISSUE TITLE
Documentation: Unable to open project after cloning

### ISSUE THREAD

**Issue by orrblue** [kpwelsh/RobotArmTeleoperation#6]
I followed the instructions under: Initializing the Unity Project. After step 3, I started the project but it says there are compilation errors, and gives the option to open the project in safe mode (for fixing the errors). 
Opening in safe mode, below are the errors and warnings. After exiting safe mode (just to see what happens), the compilation continues and the errors are still present.
![IMG_3088](https://user-images.githubusercontent.com/11370512/168897025-31e2de16-a47c-410c-a995-ec72aaab684a.jpg)
.

**Comment by kpwelsh** [comment]
Not sure what is going on there. Best guess is the current version on
GitHub is broken :).

I'm pushing an update later today that happens to remove the Endpoint
class. Should be fixed then.

**Comment by kpwelsh** [comment]
Fixed with commit 6e8cc5d2d30bf5a6eb8666eb0e3ca343d46611f2
